# Explore, Visualize, and Predict using Pandas & Jupyter

### Learn to import, explore, and tweak your data

Matt Harrison (@\_\_mharrison\_\_)

The pandas library is very popular among data scientists, quants, Excel junkies, and Python developers because it allows you to perform data ingestion, exporting, transformation, and visualization with ease. But if you are only familiar with Python, pandas may present some challenges. Since pandas is inspired by Numpy, its syntax conventions can be confusing to Python developers.

If you have questions on Python syntax, check out https://github.com/mattharrison/Tiny-Python-3.6-Notebook

Much of this content is based on my Pandas book, [*Learning the Pandas Library*](https://www.amazon.com/Learning-Pandas-Library-Munging-Analysis/dp/153359824X/ref=sr_1_3?ie=UTF8&qid=1505448275&sr=8-3&keywords=python+pandas)

NameError: name 'h' is not defined

# Jupyter Intro

Jupyter notebook is an environment for combining interactive coding and text in a webbrowser. This allows us to easily share code as well as narrative around that code. An example that was popular in the scientific community was [the discovery of gravitational waves.](https://losc.ligo.org/s/events/GW150914/GW150914_tutorial.html)

The name Jupyter is a rebranding of an open source project previously known as iPython Notebook. The rebranding was to emphasize that although the backend is written in Python, it supports various *kernals* to run other languages, including Julia (the "Ju" portion), Python ("pyt"), and R ("er"). All popular *data science* programming languages.

The architecture of Jupyter includes a server running various kernals. Using a *notebook* we can interact with a kernal. Typically we use a webbrowser to do this, but there are other iterfaces, such as an emacs mode (ein).

## Using Jupyter

After we create a notebook, we are presented with a page with an empty cell. The cell will have a blue outline, ane the text:

    In [ ]: 
    
on the side. The blue outline indicates that we are in *command mode*. There are two modes in Jupyter, command mode and *edit mode*.

To enter edit mode simply hit the enter or return key. You will notice that the outline will change to green. In edit mode, with a Python kernel, we can type Python code. Type:

    print("hello world")
    
You will notice that unlike a normal Python REPL, this will note print anything after hitting return again. To *execute* the cell, you need to hold down control and hit enter (``C-Enter``). This will run the code, print the results of the cell and put you back into edit mode.     

## Edit Mode

To enter *Edit Mode* you need to click on a cell or hit enter when it is surrounded by the blue outline. You will see that it goes green if you are in edit mode. In edit mode you have basic editing functionality. A few keys to know:

* Ctr-Enter - Run cell (execute Python code, render Markdown)
* ESC - Go back to command mode
* TAB - Tab completion
* Shift-TAB - Bring up tooltip (ESC to dismiss)


## Command Mode

*Command Mode* gives to the ability to create, copy, paste, move, and execute cells. A few keys to know:

* h - Bring up help (ESC to dismiss)
* b - Create cell below
* a - Create cell above
* c - Copy cell
* v - Paste cell below
* Enter - Go into Edit Mode
* m - Change cell type to Markdown
* y - Change cell type to code
* ii - Interrupt kernel
* oo - Restart kernel

## Cell Types

* Code
* Markdown


## Markdown

Can make *italicized*, **bold**, and ``monospaced text``:

    Can make *italicized*, **bold**, and ``monospaced text``


Headers:

    # H1
    ## H2
    ### H3
 
Lists:

    * First item
    * Second item
    
Code:

    If you indent by four spaces you have code:
    
        def add(x, y):
            return x + yt
    
## Cell Magic

type and run ``%lsmagic`` in a cell.

Common magics include:

* ``%%time`` - time how long it takes to run cell
* ``%%!`` - run shell command
* ``%matplotlib inline`` - show matplotlib plots


## IPython Help
Add ? after function, method, etc for documentation (can also run shift-tab 4 times in notebook). Add ?? after function, method, etc to see the source.

# Setup

In [ ]:
import pandas as pd
import matplotlib
import numpy as np

pd.__version__, matplotlib.__version__, np.__version__

In [ ]:
# test for unicode
'\N{SNAKE}'

In [ ]:
import sys
sys.getdefaultencoding()

In [ ]:
sys.version

# Pandas Intro

## Installation

Presumably, you have pandas installed if you ran the cell after **Setup** successfully. The Anaconda distribution is a common way to get the Python scientific stack up and running quickly on most platforms. Running ``pip install pandas`` works as well.

In [ ]:
# pandas has two main datatypes: a Series and a DataFrame
# A Series is like a column from a spreadsheet

s = pd.Series([0, 4, 6, 7])

In [ ]:
# A DataFrame is like a spreadsheet

df = pd.DataFrame({'name': ['Fred', 'Johh', 'Joe', 'Abe'], 'age': s})

In [ ]:
# We can do tab completion on objects that exist (shift tab brings up tooltip)
# ?? brings up source
df.

# Datasets

For this class we will look at some time series data. The class will look at Central Park weather. The assignments will deal with El Nino data.

## Central Park


https://pastebin.com/vaB6QQGp

## El Nino

https://archive.ics.uci.edu/ml/datasets/El+Nino

In [5]:
%matplotlib inline
# I typically start with imports like this including the matplotlib magic 
# for most notebooks
import pandas as pd
import numpy as np

# Getting Data
There are various ``pd.read_`` functions for ingesting data

In [6]:
# not necessary if you started jupyter from the project directory
%ls data/
# should have central-park-raw.csv

Invalid switch - "".

In [10]:
# if you execute this cell it will bring up a tooltip due to
# the ? at the end. You can also hit shift-tab 4 times
# if your cursor is after the v
# Hit escape to dismiss the tooltip
pd.read_csv?

In [8]:
# let's load the data and treat column 0 as a date
nyc = pd.read_csv('data/central-park-raw.csv', parse_dates=[0])
# Jupyter will print the result of the last command
nyc

,EST,Max TemperatureF,Mean TemperatureF,Min TemperatureF,Max Dew PointF,MeanDew PointF,Min DewpointF,Max Humidity,Mean Humidity,Min Humidity,...,Max VisibilityMiles,Mean VisibilityMiles,Min VisibilityMiles,Max Wind SpeedMPH,Mean Wind SpeedMPH,Max Gust SpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,2006-01-01,42.0,37.0,32.0,32.0,30.0,28.0,85.0,74.0,62.0,...,10.0,10.0,8.0,9.0,3.0,10.0,0.00,8.0,NaN,276.0
1,2006-01-02,48.0,44.0,39.0,38.0,34.0,29.0,92.0,71.0,49.0,...,10.0,8.0,4.0,18.0,5.0,24.0,0.63,5.0,Rain,76.0
2,2006-01-03,40.0,37.0,33.0,38.0,33.0,26.0,92.0,84.0,75.0,...,10.0,7.0,2.0,28.0,15.0,41.0,1.13,8.0,Rain,39.0
3,2006-01-04,38.0,34.0,29.0,36.0,26.0,19.0,85.0,72.0,59.0,...,10.0,10.0,4.0,15.0,7.0,20.0,0.00,3.0,NaN,70.0
4,2006-01-05,50.0,44.0,37.0,38.0,35.0,32.0,92.0,71.0,50.0,...,10.0,6.0,2.0,15.0,5.0,21.0,0.05,6.0,Rain,251.0
5,2006-01-06,43.0,37.0,30.0,33.0,24.0,14.0,73.0,60.0,47.0,...,10.0,10.0,10.0,17.0,6.0,25.0,0.00,7.0,NaN,317.0
6,2006-01-07,35.0,30.0,25.0,19.0,14.0,11.0,60.0,51.0,41.0,...,10.0,10.0,10.0,15.0,7.0,23.0,0.00,2.0,NaN,267.0
7,2006-01-08,46.0,40.0,34.0,35.0,25.0,19.0,70.0,56.0,41.0,...,10.0,10.0,10.0,13.0,5.0,17.0,0.00,3.0,NaN,192.0
8,2006-01-09,60.0,52.0,43.0,39.0,36.0,30.0,76.0,60.0,44.0,...,10.0,10.0,10.0,15.0,8.0,24.0,0.00,1.0,NaN,249.0
9,2006-01-10,49.0,45.0,41.0,31.0,28.0,26.0,62.0,52.0,42.0,...,10.0,10.0,10.0,10.0,6.0,16.0,0.00,1.0,NaN,261.0
10,2006-01-11,52.0,47.0,42.0,50.0,42.0,30.0,96.0,79.0,62.0,...,10.0,4.0,1.0,14.0,4.0,21.0,0.23,7.0,Rain,71.0
11,2006-01-12,57.0,51.0,45.0,45.0,36.0,31.0,89.0,63.0,36.0,...,10.0,10.0,10.0,15.0,7.0,20.0,0.00,0.0,NaN,246.0
12,2006-01-13,54.0,49.0,43.0,52.0,43.0,39.0,96.0,81.0,66.0,...,10.0,4.0,1.0,12.0,3.0,17.0,0.00,5.0,NaN,171.0
13,2006-01-14,57.0,44.0,31.0,55.0,49.0,26.0,100.0,91.0,82.0,...,10.0,5.0,1.0,18.0,9.0,36.0,1.17,8.0,Rain,158.0
14,2006-01-15,32.0,24.0,16.0,25.0,12.0,-1.0,92.0,62.0,32.0,...,10.0,6.0,0.0,31.0,13.0,39.0,0.12,5.0,Fog-Snow,298.0
15,2006-01-16,32.0,24.0,16.0,9.0,5.0,1.0,54.0,44.0,33.0,...,10.0,10.0,10.0,16.0,8.0,24.0,0.00,0.0,NaN,279.0
16,2006-01-17,44.0,35.0,26.0,39.0,21.0,8.0,82.0,59.0,35.0,...,10.0,9.0,2.0,14.0,6.0,20.0,0.16,5.0,Rain,67.0
17,2006-01-18,58.0,47.0,36.0,55.0,43.0,19.0,93.0,69.0,44.0,...,10.0,6.0,2.0,28.0,12.0,41.0,0.59,7.0,Rain,217.0
18,2006-01-19,47.0,41.0,34.0,27.0,21.0,18.0,56.0,47.0,37.0,...,10.0,10.0,10.0,17.0,8.0,23.0,0.00,0.0,NaN,244.0
19,2006-01-20,61.0,52.0,42.0,36.0,32.0,28.0,62.0,49.0,36.0,...,10.0,10.0,10.0,16.0,8.0,23.0,0.00,0.0,NaN,233.0
20,2006-01-21,63.0,51.0,38.0,42.0,32.0,18.0,61.0,53.0,44.0,...,10.0,10.0,10.0,26.0,10.0,39.0,0.00,2.0,NaN,263.0
21,2006-01-22,43.0,38.0,33.0,26.0,16.0,11.0,52.0,40.0,27.0,...,10.0,10.0,10.0,15.0,7.0,23.0,0.00,1.0,NaN,49.0
22,2006-01-23,40.0,38.0,35.0,38.0,35.0,28.0,92.0,76.0,59.0,...,10.0,7.0,2.0,14.0,4.0,17.0,0.68,7.0,Rain-Snow,51.0
23,2006-01-24,46.0,41.0,35.0,30.0,26.0,15.0,76.0,54.0,31.0,...,10.0,10.0,10.0,14.0,7.0,18.0,0.00,1.0,NaN,185.0
24,2006-01-25,42.0,38.0,34.0,32.0,26.0,18.0,82.0,65.0,47.0,...,10.0,10.0,10.0,22.0,10.0,32.0,0.00,4.0,NaN,266.0
25,2006-01-26,35.0,31.0,26.0,19.0,14.0,10.0,56.0,47.0,38.0,...,10.0,10.0,10.0,21.0,14.0,30.0,0.00,1.0,NaN,292.0
26,2006-01-27,43.0,34.0,24.0,15.0,10.0,4.0,60.0,40.0,19.0,...,10.0,10.0,10.0,16.0,8.0,22.0,0.00,0.0,NaN,274.0
27,2006-01-28,58.0,48.0,37.0,27.0,20.0,14.0,40.0,33.0,26.0,...,10.0,10.0,10.0,13.0,6.0,21.0,0.00,0.0,NaN,243.0
28,2006-01-29,53.0,49.0,44.0,49.0,39.0,26.0,93.0,66.0,38.0,...,10.0,8.0,2.0,13.0,5.0,20.0,0.14,5.0,Rain,169.0
29,2006-01-30,64.0,53.0,41.0,48.0,43.0,39.0,96.0,70.0,43.0,...,10.0,6.0,2.0,20.0,8.0,28.0,0.01,4.0,NaN,64.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3257,2014-12-02,43.0,39.0,35.0,40.0,30.0,17.0,89.0,67.0,44.0,...,10.0,8.0,2.0,17.0,9.0,26.0,0.08,7.0,Rain,70.0
3258,2014-12-03,46.0,44.0,41.0,43.0,38.0,24.0,92.0,73.0,53.0,...,10.0,6.0,2.0,16.0,8.0,26.0,0.06,7.0,Rain,276.0
3259,2014-12-04,45.0,41.0,37.0,24.0,21.0,17.0,59.0,48.0,36.0,...,10.0,10.0,10.0,13.0,6.0,19.0,0.00,0.0,NaN,304.0
3260,2014-12-05,44.0,39.0,34.0,41.0,33.0,19.0,89.0,69.0,48.0,...,10.0,6.0,1.0,17.0,6.0,21.0,0.51,6.0,Rain,50.0
3261,2014-12-06,50.0,45.0,39.0,47.0,42.0,36.0,96.0,88.0,80.0,...,8.0,3.0,1.0,17.0,4.0,30.0,1.22,8.0,Rain,36.0
3262,2014-12-07,42.0,36.0,30.0,35.0,18.0,0.0,92.0,62.0,32.0,...,10.0,10.0,10.0,25.0,12.0,40.0,0.04,1.0,Rain,28.0
3263,2014-12-08,37.0,31.0,24.0,30.0,17.0,-1.0,75.0,51.0,27.0,...,10.0,10.0,10.0,20.0,12.0,29.0,0.00,6.0,NaN,60.0
3264,2014-12-09,42.0,39.0,36.0,38.0,36.0,30.0,92.0,81.0,70.0,...,10.0,5.0,1.0,22.0,10.0,32.0,2.54,8.0,Rain,36.0
3265,2014-12-10,40.0,36.0,32.0,36.0,31.0,23.0,89.0,74.0,59.0,...,10.0,6.0,1.0,16.0,8.0,24.0,0.08,8.0,Rain-Snow,295.0
3266,2014-12-11,38.0,35.0,31.0,26.0,23.0,20.0,75.0,62.0,48.0,...,10.0,9.0,2.0,17.0,8.0,25.0,0.01,7.0,Snow,276.0
3267,2014-12-12,38.0,35.0,32.0,23.0,21.0,19.0,61.0,57.0,52.0,...,10.0,10.0,10.0,15.0,8.0,25.0,0.00,6.0,NaN,303.0
3268,2014-12-13,44.0,39.0,34.0,28.0,25.0,21.0,64.0,54.0,43.0,...,10.0,10.0,10.0,16.0,9.0,28.0,0.00,2.0,NaN,307.0
3269,2014-12-14,46.0,42.0,38.0,29.0,29.0,28.0,70.0,60.0,49.0,...,10.0,10.0,10.0,13.0,6.0,20.0,0.00,4.0,NaN,306.0
3270,2014-12-15,48.0,43.0,37.0,34.0,29.0,28.0,70.0,58.0,46.0,...,10.0,10.0,10.0,8.0,3.0,12.0,0.00,0.0,NaN,333.0
3271,2014-12-16,49.0,44.0,38.0,43.0,39.0,32.0,86.0,76.0,65.0,...,10.0,6.0,2.0,12.0,4.0,14.0,0.20,7.0,Rain,75.0
3272,2014-12-17,54.0,48.0,42.0,43.0,39.0,26.0,92.0,73.0,53.0,...,10.0,7.0,2.0,16.0,6.0,26.0,0.02,7.0,Rain,294.0
3273,2014-12-18,42.0,40.0,37.0,25.0,23.0,21.0,59.0,52.0,45.0,...,10.0,10.0,10.0,16.0,9.0,28.0,0.00,6.0,NaN,293.0
3274,2014-12-19,38.0,35.0,31.0,25.0,21.0,19.0,63.0,56.0,48.0,...,10.0,10.0,10.0,14.0,7.0,24.0,0.00,5.0,NaN,307.0
3275,2014-12-20,33.0,32.0,30.0,21.0,19.0,18.0,63.0,57.0,51.0,...,10.0,10.0,10.0,12.0,5.0,15.0,0.00,8.0,NaN,10.0
3276,2014-12-21,36.0,34.0,31.0,29.0,25.0,21.0,82.0,73.0,63.0,...,10.0,9.0,6.0,9.0,5.0,13.0,T,8.0,Snow,338.0
3277,2014-12-22,44.0,40.0,35.0,42.0,35.0,29.0,89.0,82.0,75.0,...,10.0,8.0,5.0,12.0,6.0,16.0,0.04,8.0,Rain,59.0
3278,2014-12-23,46.0,45.0,43.0,44.0,42.0,41.0,96.0,91.0,86.0,...,9.0,3.0,2.0,17.0,8.0,26.0,0.16,8.0,Rain,67.0
3279,2014-12-24,58.0,51.0,44.0,57.0,47.0,43.0,100.0,96.0,92.0,...,7.0,3.0,1.0,12.0,6.0,17.0,0.80,8.0,Rain,86.0
3280,2014-12-25,62.0,53.0,44.0,60.0,40.0,27.0,100.0,69.0,38.0,...,10.0,8.0,2.0,20.0,10.0,32.0,0.09,5.0,Rain,279.0
3281,2014-12-26,50.0,45.0,40.0,29.0,28.0,27.0,64.0,53.0,42.0,...,10.0,10.0,10.0,13.0,6.0,18.0,0.00,0.0,NaN,272.0
3282,2014-12-27,55.0,50.0,44.0,35.0,31.0,29.0,53.0,47.0,41.0,...,10.0,10.0,10.0,14.0,4.0,25.0,0.00,0.0,NaN,257.0
3283,2014-12-28,54.0,49.0,43.0,43.0,37.0,26.0,92.0,73.0,53.0,...,10.0,9.0,2.0,15.0,6.0,22.0,0.10,5.0,Rain,264.0
3284,2014-12-29,44.0,39.0,34.0,25.0,19.0,15.0,53.0,42.0,31.0,...,10.0,10.0,10.0,15.0,5.0,25.0,0.00,0.0,NaN,308.0
3285,2014-12-30,34.0,31.0,28.0,17.0,13.0,8.0,58.0,47.0,36.0,...,10.0,10.0,10.0,10.0,4.0,17.0,0.00,2.0,NaN,5.0
3286,2014-12-31,32.0,30.0,27.0,12.0,8.0,5.0,55.0,43.0,30.0,...,10.0,10.0,10.0,14.0,6.0,21.0,0.00,2.0,NaN,275.0

In [9]:
# dataframes can get big, so only show the first bit
nyc.head()

,EST,Max TemperatureF,Mean TemperatureF,Min TemperatureF,Max Dew PointF,MeanDew PointF,Min DewpointF,Max Humidity,Mean Humidity,Min Humidity,...,Max VisibilityMiles,Mean VisibilityMiles,Min VisibilityMiles,Max Wind SpeedMPH,Mean Wind SpeedMPH,Max Gust SpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,2006-01-01,42.0,37.0,32.0,32.0,30.0,28.0,85.0,74.0,62.0,...,10.0,10.0,8.0,9.0,3.0,10.0,0.00,8.0,NaN,276.0
1,2006-01-02,48.0,44.0,39.0,38.0,34.0,29.0,92.0,71.0,49.0,...,10.0,8.0,4.0,18.0,5.0,24.0,0.63,5.0,Rain,76.0
2,2006-01-03,40.0,37.0,33.0,38.0,33.0,26.0,92.0,84.0,75.0,...,10.0,7.0,2.0,28.0,15.0,41.0,1.13,8.0,Rain,39.0
3,2006-01-04,38.0,34.0,29.0,36.0,26.0,19.0,85.0,72.0,59.0,...,10.0,10.0,4.0,15.0,7.0,20.0,0.00,3.0,NaN,70.0
4,2006-01-05,50.0,44.0,37.0,38.0,35.0,32.0,92.0,71.0,50.0,...,10.0,6.0,2.0,15.0,5.0,21.0,0.05,6.0,Rain,251.0

## Getting Data Assignment

For your assignment, you will look at El Nino data.

The [website](https://archive.ics.uci.edu/ml/datasets/El+Nino)  states:

    The data is stored in an ASCII files with one observation per line. Spaces separate fields and periods (.) denote missing values.


Load the ``data/tao-all2.dat.gz`` file into a data frame using ``pd.read_csv``.
Use the ``names`` variable for the initial column names (taken from website).
Replace empty values (``.``) with ``NaN``. Pull the year, month, and date columns into a single variable using the ``parse_dates`` parameter (see the ``pd.read_csv`` docs for info on this).

In [21]:
names='''obs
year
month
day
date
latitude
longitude
zon.winds
mer.winds
humidity
air temp.
s.s.temp.'''.split('\n')

names

['obs',
 'year',
 'month',
 'day',
 'date',
 'latitude',
 'longitude',
 'zon.winds',
 'mer.winds',
 'humidity',
 'air temp.',
 's.s.temp.']

In [34]:
nino = pd.read_csv('data/tao-all2.dat.gz', sep=' ', names=names, na_values='.', parse_dates=[[1,2,3]])

In [35]:
nino

,year_month_day,obs,date,latitude,longitude,zon.winds,mer.winds,humidity,air temp.,s.s.temp.
0,1980-03-07,1,800307,-0.02,-109.46,-6.8,0.7,NaN,26.14,26.24
1,1980-03-08,2,800308,-0.02,-109.46,-4.9,1.1,NaN,25.66,25.97
2,1980-03-09,3,800309,-0.02,-109.46,-4.5,2.2,NaN,25.69,25.28
3,1980-03-10,4,800310,-0.02,-109.46,-3.8,1.9,NaN,25.57,24.31
4,1980-03-11,5,800311,-0.02,-109.46,-4.2,1.5,NaN,25.30,23.19
5,1980-03-12,6,800312,-0.02,-109.46,-4.4,0.3,NaN,24.72,23.64
6,1980-03-13,7,800313,-0.02,-109.46,-3.2,0.1,NaN,24.66,24.34
7,1980-03-14,8,800314,-0.02,-109.46,-3.1,0.6,NaN,25.17,24.14
8,1980-03-15,9,800315,-0.02,-109.46,-3.0,1.0,NaN,25.59,24.24
9,1980-03-16,10,800316,-0.02,-109.46,-1.2,1.0,NaN,26.71,25.94
10,1980-03-17,11,800317,-0.02,-109.46,-0.1,0.7,NaN,27.28,26.65
11,1980-03-18,12,800318,-0.02,-109.46,-1.2,2.3,NaN,26.86,27.13
12,1980-03-19,13,800319,-0.02,-109.46,-4.1,-0.3,NaN,26.38,26.35
13,1980-03-20,14,800320,-0.02,-109.46,-4.8,-0.8,NaN,26.19,25.87
14,1980-03-21,15,800321,-0.02,-109.46,-5.2,2.0,NaN,26.08,25.38
15,1980-03-22,16,800322,-0.02,-109.46,-2.7,2.7,NaN,26.24,NaN
16,1980-03-23,17,800323,-0.02,-109.46,-4.4,1.1,NaN,26.05,NaN
17,1980-03-24,18,800324,-0.02,-109.46,-4.3,0.7,NaN,25.67,NaN
18,1980-03-25,19,800325,-0.02,-109.46,-3.8,0.5,NaN,25.39,NaN
19,1980-03-26,20,800326,-0.02,-109.46,-3.0,0.2,NaN,25.17,NaN
20,1980-03-27,21,800327,-0.02,-109.46,-3.2,-0.2,NaN,25.25,NaN
21,1980-03-28,22,800328,-0.02,-109.46,-1.9,0.7,NaN,25.35,NaN
22,1980-03-29,23,800329,-0.02,-109.46,-0.8,0.3,NaN,26.13,NaN
23,1980-08-11,24,800811,0.00,-109.56,-3.3,1.5,NaN,21.48,21.81
24,1980-08-12,25,800812,0.00,-109.56,-3.5,0.8,NaN,21.27,21.58
25,1980-08-13,26,800813,0.00,-109.56,-4.9,1.9,NaN,21.11,21.32
26,1980-08-14,27,800814,0.00,-109.56,-1.2,2.1,NaN,20.95,21.19
27,1980-08-15,28,800815,0.00,-109.56,-1.2,2.7,NaN,21.76,21.47
28,1980-08-16,29,800816,0.00,-109.56,-1.9,2.7,NaN,22.11,21.89
29,1980-08-17,30,800817,0.00,-109.56,-4.2,0.7,NaN,21.69,21.85
...,...,...,...,...,...,...,...,...,...,...
178050,1998-05-17,178051,980517,8.96,-140.33,-5.3,-4.7,82.2,27.01,27.57
178051,1998-05-18,178052,980518,8.96,-140.32,-5.4,-4.3,82.2,27.09,27.59
178052,1998-05-19,178053,980519,8.95,-140.33,-6.4,-5.3,84.7,27.28,27.54
178053,1998-05-20,178054,980520,8.96,-140.34,-8.3,-6.0,83.0,27.28,27.48
178054,1998-05-21,178055,980521,8.96,-140.33,-7.7,-6.3,89.8,27.24,27.52
178055,1998-05-22,178056,980522,8.96,-140.32,-7.3,-6.4,86.4,27.40,27.53
178056,1998-05-23,178057,980523,8.96,-140.32,-6.3,-6.4,83.5,27.32,27.57
178057,1998-05-24,178058,980524,8.95,-140.32,-5.7,-3.6,86.4,26.70,27.62
178058,1998-05-25,178059,980525,8.96,-140.32,-6.2,-5.8,83.0,27.36,27.68
178059,1998-05-26,178060,980526,8.96,-140.34,-6.4,-5.3,82.2,27.32,27.70
178060,1998-05-27,178061,980527,8.96,-140.33,-4.9,-6.2,87.3,27.09,27.85
178061,1998-05-28,178062,980528,8.96,-140.33,-6.3,-4.9,91.5,26.82,27.98
178062,1998-05-29,178063,980529,8.97,-140.32,-6.7,-3.7,94.1,26.62,28.04
178063,1998-05-30,178064,980530,8.96,-140.33,-6.3,-4.8,92.0,26.89,27.98
178064,1998-05-31,178065,980531,8.97,-140.33,-6.3,-4.9,86.9,27.44,28.13
178065,1998-06-01,178066,980601,8.97,-140.32,-4.2,-2.5,87.3,26.62,28.14
178066,1998-06-02,178067,980602,8.96,-140.32,-6.8,-2.4,86.0,27.60,28.09
178067,1998-06-03,178068,980603,8.96,-140.33,-7.1,-3.2,82.2,27.87,28.15
178068,1998-06-04,178069,980604,8.96,-140.33,-6.7,-4.7,81.3,27.75,28.19
178069,1998-06-05,178070,980605,8.96,-140.32,-6.4,-5.7,82.6,27.75,28.24
178070,1998-06-06,178071,980606,8.96,-140.33,-6.6,-4.3,81.3,27.71,28.28
178071,1998-06-07,178072,980607,8.95,-140.33,-8.4,-4.2,83.5,27.91,28.26
178072,1998-06-08,178073,980608,8.96,-140.33,-8.4,-5.0,79.2,27.87,28.22
178073,1998-06-09,178074,980609,8.98,-140.33,-6.5,-5.9,75.4,27.56,28.22
178074,1998-06-10,178075,980610,8.95,-140.33,-6.8,-5.3,81.3,27.52,28.17
178075,1998-06-11,178076,980611,8.96,-140.33,-5.1,-0.4,94.1,26.04,28.14
178076,1998-06-12,178077,980612,8.96,-140.32,-4.3,-3.3,93.2,25.80,27.87
178077,1998-06-13,178078,980613,8.95,-140.34,-6.1,-4.8,81.3,27.17,27.93
178078,1998-06-14,178079,980614,8.96,-140.33,-4.9,-2.3,76.2,27.36,28.03
178079,1998-06-15,178080,980615,8.95,-140.33,NaN,NaN,NaN,27.09,28.09

# Inspecting Data

In [36]:
# Interesting aside, the columns are actually an Index 
nyc.columns

Index(['EST', 'Max TemperatureF', 'Mean TemperatureF', 'Min TemperatureF',
       'Max Dew PointF', 'MeanDew PointF', 'Min DewpointF', 'Max Humidity',
       ' Mean Humidity', ' Min Humidity', ' Max Sea Level PressureIn',
       ' Mean Sea Level PressureIn', ' Min Sea Level PressureIn',
       ' Max VisibilityMiles', ' Mean VisibilityMiles', ' Min VisibilityMiles',
       ' Max Wind SpeedMPH', ' Mean Wind SpeedMPH', ' Max Gust SpeedMPH',
       'PrecipitationIn', ' CloudCover', ' Events', ' WindDirDegrees'],
      dtype='object')

In [37]:
# If is good to know if columns have a [correct] type, (object could mean string)
nyc.dtypes

EST                           datetime64[ns]
Max TemperatureF                     float64
Mean TemperatureF                    float64
Min TemperatureF                     float64
Max Dew PointF                       float64
MeanDew PointF                       float64
Min DewpointF                        float64
Max Humidity                         float64
 Mean Humidity                       float64
 Min Humidity                        float64
 Max Sea Level PressureIn            float64
 Mean Sea Level PressureIn           float64
 Min Sea Level PressureIn            float64
 Max VisibilityMiles                 float64
 Mean VisibilityMiles                float64
 Min VisibilityMiles                 float64
 Max Wind SpeedMPH                   float64
 Mean Wind SpeedMPH                  float64
 Max Gust SpeedMPH                   float64
PrecipitationIn                       object
 CloudCover                          float64
 Events                               object
 WindDirDegrees                      float64
dtype: object

In [ ]:
# we can also see how much space is taken up
nyc.info()

In [ ]:
# just view the first 10 rows
nyc.head(10)

In [ ]:
# Transposing the data often makes it easier to view
nyc.T  # nyc.transpose()

In [ ]:
# Here is the size (num rows, num cols)
nyc.shape

In [ ]:
# We can inspect the index
nyc.index

In [ ]:
# We can use the .set_index method to use another column as the index
nyc.set_index('EST')

In [ ]:
# undo .set_index with .reset_index
nyc.set_index('EST').reset_index()

## Inspecting Data Assignment

Now it is your turn to inspect the El Nino data.
 
* What are the columns of the dataframe?
* What are the types of the columns?
* How would you print the first 10 rows of data?
* How would you transpose the data?
* What is the shape of the data?
* How would we inspect the index?

# Tweak Data

  *In Data Science, 80% of time spent prepare data, 20% of time spent complain about need for  prepare data.*
  
  -@bigdataborat
  
Let's see how we spend 80% of our time.

In [ ]:
# I like to start by inspecting the columns. Pandas will try to 
# infer types from CSV files, but doesn't always do the right thing.
# Sometimes the data is just messy.
nyc.dtypes

In [ ]:
# See those spaces in front of some of the Columns?
# Remove spaces from front/end of column names
nyc.columns = [x.strip() for x in nyc.columns]

In [ ]:
# Use underscores to enable attribute access/jupyter completion
nyc.columns = [x.replace(' ', '_') for x in nyc.columns]

In [ ]:
# For non-numeric columns, .value_counts gives us 
# counts of the data. One would think that 
# PrecipitationIn should be numeric....
nyc.PrecipitationIn.value_counts()

In [ ]:
# There is a "T" in there. Trace? 
# Convert "T" to 0.001
nyc.PrecipitationIn.replace("T", '0.001')
# Convert to numeric data
nyc.PrecipitationIn = pd.to_numeric(nyc.PrecipitationIn.replace("T", '0.001'))

In [ ]:
nyc.Events.value_counts()

In [ ]:
# can perform string operations on string columns off of the "str" attribute
nyc.Events.str.upper()

In [ ]:
# Looks like the type of this column is mixed
type(nyc.Events[0])

In [ ]:
set(nyc.Events.apply(type))

In [ ]:
# Replace nan with ''
nyc['Events'] = nyc.Events.fillna('')

In [ ]:
set(nyc.Events.apply(type))

In [ ]:
# convert inches to cm
# If we multiply a column (Series), we are *broadcasting*
# the operation to every cell
nyc.PrecipitationIn * 2.54

In [ ]:
# can also apply an arbitrary function, though this will be slow as it is not vectorized
#   map - works with a dictionary (mapping value to new value),  series (like dict), function
#   apply - only works with function as a parameter. Allows extra parameters
#   aggregate (agg) - works with function or list of functions. If reducing function, returns a scalar.
#   transform - wraps agg and won't do a reduction
def to_cm(val):
    return val * 2.54

nyc.PrecipitationIn.transform(to_cm)

In [ ]:
%%timeit
nyc.PrecipitationIn.map(to_cm)

In [ ]:
%%timeit
nyc.PrecipitationIn.transform(to_cm)

In [ ]:
%%timeit
nyc.PrecipitationIn*2.54

In [ ]:
# can add and drop columns (axis=1 means along the columns axis)
# Note that we can access some columns with attribute access
# We can only set w/ attribute access on an existing column!
nyc['State'] = 'NYC'
nyc = nyc.drop(['State'], axis=1)
nyc

In [ ]:
# can use pd.to_datetime to convert a column to a datetime
date_str = nyc.EST.astype(str)
pd.to_datetime(date_str)

## Tweak Data Assignment
With the nino dataset:
* Replace the periods and spaces in the column names with underscores
* The temperatures are stored as Celsius. Create a new column, ``air_temp_F``, using Fahrenheit
  (Tf = Tc*9/5 + 32)
* The wind speed is in meters per second. Create new columns,  adding ``_mph``, that uses miles per hour ( 1 MPS = 2.237 MPH )
* Convert the ``date`` column to a date type.
* Drop the obs column

In [44]:
dir(nyc)

['EST',
 'PrecipitationIn',
 'T',
 '_AXIS_ALIASES',
 '_AXIS_IALIASES',
 '_AXIS_LEN',
 '_AXIS_NAMES',
 '_AXIS_NUMBERS',
 '_AXIS_ORDERS',
 '_AXIS_REVERSED',
 '_AXIS_SLICEMAP',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_wrap__',
 '__bool__',
 '__bytes__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__unicode__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_add_numeric_operations',
 '_add_series_only_operations',
 '_add_series_or_dataframe_operations',
 '_agg_by_level',
 '_agg_doc',
 '_aggregate',
 '_aggregate_multiple_funcs',
 '_align_frame',
 '_align_series',
 '_box_col_values',
 '_box_item_values',
 '_builtin_table',
 '_check_inplace_setting',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_percentile',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_combine_const',
 '_combine_frame',
 '_combine_match_columns',
 '_combine_match_index',
 '_compare_frame',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_axes_dict_for_slice',
 '_construct_axes_dict_from',
 '_construct_axes_from_arguments',
 '_constructor',
 '_constructor_expanddim',
 '_constructor_sliced',
 '_convert',
 '_count_level',
 '_create_indexer',
 '_cython_table',
 '_deprecations',
 '_dir_additions',
 '_dir_deletions',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_valid_index',
 '_expand_axes',
 '_find_valid_index',
 '_from_arrays',
 '_from_axes',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cacher',
 '_get_index_resolvers',
 '_get_item_cache',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_get_values',
 '_getitem_array',
 '_getitem_column',
 '_getitem_frame',
 '_getitem_multilevel',
 '_getitem_slice',
 '_gotitem',
 '_iget_item_cache',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_dict',
 '_init_mgr',
 '_init_ndarray',
 '_internal_names',
 '_internal_names_set',
 '_is_builtin_func',
 '_is_cached',
 '_is_copy',
 '_is_cython_func',
 '_is_datelike_mixed_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_numeric_mixed_type',
 '_is_view',
 '_ix',
 '_ixs',
 '_join_compat',
 '_maybe_cache_changed',
 '_maybe_update_cacher',
 '_metadata',
 '_needs_reindex_multi',
 '_obj_with_exclusions',
 '_protect_consolidate',
 '_reduce',
 '_reindex_axes',
 '_reindex_axis',
 '_reindex_columns',
 '_reindex_index',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_sanitize_column',
 '_selected_obj',
 '_selection',
 '_selection_list',
 '_selection_name',
 '_series',
 '_set_as_cached',
 '_set_axis',
 '_set_axis_name',
 '_set_is_copy',
 '_set_item',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_setup_axes',
 '_shallow_copy',
 '_slice',
 '_stat_axis',
 '_stat_axis_name',
 '_stat_axis_number',
 '_take',
 '_to_dict_of_blocks',
 '_try_aggregate_string_function',
 '_typ',
 '_unpickle_frame_compat',
 '_unpickle_matrix_compat',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 '_xs',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'append',
 'apply',
 'applymap',
 'as_matrix',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'axes',
 'between_time',
 'bfill',
 'bool',
 'boxplot',
 'clip',
 'clip_lower',
 'clip_upper',
 'columns',
 'combine',
 'combine_first',
 'compound',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'eval',
 'ewm',
 'expanding',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'floordiv',
 'from_dict',
 'from_records',
 'ftypes',
 'ge',
 'get',
 'get_dtype_counts',
 'get_ftype_counts',
 'get_values',
 'groupby',
 'gt',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isin',
 'isna',
 'isnull',
 'items',
 'iteritems',
 'iterrows',
 'itertuples',
 'ix',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'loc',
 'lookup',
 'lt',
 'mad',
 'mask',
 'max',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pct_change',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'query',
 'radd',
 'rank',
 'rdiv',
 'reindex',
 'reindex_axis',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'select',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_index',
 'shape',
 'shift',
 'size',
 'skew',
 'slice_shift',
 'sort_index',
 'sort_values',
 'squeeze',
 'stack',
 'std',
 'style',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dense',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_gbq',
 'to_hdf',
 'to_html',
 'to_json',
 'to_latex',
 'to_msgpack',
 'to_panel',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sparse',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tshift',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'values',
 'var',
 'where',
 'xs']